const setting = [
  {
    setting: {
      number_of_image_per_product: "5",
      shop_name: "ZAPMarketplace",
      address: "59 Station Rd, Purls Bridge, United Kingdom",
      company_name: "zapmarketplace",
      vat_number: "47589",
      post_code: "2030",
      contact: "019579034",
      email: "zapmarketplace@gmail.com",
      website: "store.zapmarketplace.online",
      default_currency: "€",
      default_time_zone: "Europe/London",
      default_date_format: "MMM D, YYYY",
      receipt_size: "57-mm",
    },
    name: "globalSetting",
  },
  {
    setting: {
      navbar: {
        nav_color: "#0f6745",
        categories_menu_status: true,
        about_menu_status: true,
        contact_menu_status: true,
        offers_menu_status: true,
        term_and_condition_status: true,
        privacy_policy_status: true,
        faq_status: true,
        help_text: {
          en: "We are available 24/7, Need help?",
          de: "Wir sind erreichbar 24/7, Brauchen Sie Hilfe?",
          fr: "Nous sommes disponibles 24/7, Besoin d'aide?",
          ar: "نحن متوفرون على مدار الساعة طوال أيام الأسبوع، هل تحتاج إلى مساعدة؟",
        },
        categories: {
          en: "Categories",
          de: "Kategorien",
          fr: "Catégories",
          ar: "الفئات",
        },
        about_us: {
          en: "About Us",
          de: "Uber Uns",
          fr: "À propos de nous",
          ar: "معلومات عنا",
        },
        contact_us: {
          en: "Contact Us",
          de: "Kontaktiere Uns",
          fr: "Contactez-nous",
          ar: "اتصل بنا",
        },
        offers: {
          en: "Offers",
          de: "Bietet an",
          fr: "Offres",
          ar: "العروض",
        },
        faq: {
          en: "FAQ",
          de: "FAQ",
          fr: "FAQ",
          ar: "الأسئلة الشائعة",
        },
        privacy_policy: {
          en: "Privacy Policy",
          de: "Datenschutzrichtlinie",
          fr: "Politique de confidentialité",
          ar: "سياسة الخصوصية",
        },
        term_and_condition: {
          en: "Terms & Conditions",
          de: "Terms & Bedingungen",
          fr: "Termes et conditions",
          ar: "الشروط والأحكام",
        },
        pages: {
          en: "Pages",
          de: "Seiten",
          fr: "Pages",
          ar: "الصفحات",
        },
        my_account: {
          en: "My Account",
          de: "Mein Konto",
          fr: "Mon compte",
          ar: "حسابي",
        },
        login: {
          en: "Login",
          de: "Anmeldung",
          fr: "Connexion",
          ar: "تسجيل الدخول",
        },
        logout: {
          en: "Logout",
          de: "Ausloggen",
          fr: "Déconnexion",
          ar: "تسجيل الخروج",
        },
        checkout: {
          en: "Checkout",
          de: "Kasse",
          fr: "Paiement",
          ar: "الدفع",
        },
        phone: "+965 505 631288",
        logo: "https://res.cloudinary.com/dapzqelui/image/upload/v1701430715/images/logo-light_hls14v.svg",
      },
      home: {
        coupon_status: true,
        featured_status: true,
        daily_needs_status: true,
        slider_width_status: false,
        promotion_banner_status: true,
        delivery_status: true,
        popular_products_status: true,
        discount_product_status: true,
        feature_promo_status: true,
        discount_coupon_code: ["WINTER21", "OCTOBER21"],
        place_holder_img: "",
        discount_title: {
          en: "Latest Super Discount Active Coupon Code",
          de: "Neuester aktiver Super-Rabatt-Gutscheincode",
          fr: "Dernier code de réduction actif super promo",
          ar: "آخر كود تخفيض نشط للعروض الخاصة",
        },
        promotion_title: {
          en: "100% Natural Quality Organic Product",
          de: "100 % natürliches Bio-Qualitätsprodukt",
          fr: "Produit biologique de qualité 100% naturel",
          ar: "منتج عضوي طبيعي عالي الجودة 100٪",
        },
        promotion_description: {
          en: "See Our latest discounted products from here and get a special discount product",
          de: "Sehen Sie sich hier unsere neuesten reduzierten Produkte an und sichern Sie sich ein spezielles Rabattprodukt",
          fr: "Découvrez nos derniers produits en promotion ici et obtenez un produit en promotion spécial",
          ar: "اطلع على منتجاتنا المخفضة الأحدث من هنا واحصل على منتج خصم خاص",
        },
        promotion_button_name: {
          en: "Shop Now",
          de: "Jetzt einkaufen",
          fr: "Achetez maintenant",
          ar: "تسوق الآن",
        },
        promotion_button_link: "/search?category=breakfast",
        feature_title: {
          en: "Featured Categories",
          de: "Beliebte Kategorien",
          fr: "Catégories en vedette",
          ar: "الفئات المميزة",
        },
        feature_description: {
          en: "Choose your necessary products from this feature categories.",
          de: "Wählen Sie aus diesen Funktionskategorien die gewünschten Produkte aus.",
          fr: "Choisissez vos produits nécessaires parmi ces catégories en vedette.",
          ar: "اختر منتجاتك الضرورية من هذه الفئات المميزة.",
        },
        feature_product_limit: 18,
        popular_title: {
          en: "Popular Products for Daily Shopping",
          de: "Beliebte Produkte für den täglichen Einkauf",
          fr: "Produits populaires pour vos courses quotidiennes",
          ar: "منتجات شائعة للتسوق اليومي",
        },
        popular_description: {
          en: "See all our popular products in this week. You can choose your daily needs products from this list and get some special offer with free shipping.",
          de: "Sehen Sie sich diese Woche alle unsere beliebten Produkte an. Aus dieser Liste können Sie Produkte für den täglichen Bedarf auswählen und ein Sonderangebot mit kostenlosem Versand erhalten.",
          fr: "Découvrez tous nos produits populaires de la semaine. Vous pouvez choisir vos produits de première nécessité dans cette liste et bénéficier d'une offre spéciale avec livraison gratuite.",
          ar: "انظر إلى جميع منتجاتنا الشائعة هذا الأسبوع. يمكنك اختيار منتجات احتياجاتك اليومية من هذه القائمة والحصول على عرض خاص مع الشحن المجاني.",
        },
        popular_product_limit: 18,
        quick_delivery_subtitle: {
          en: "Organic Products and Food",
          de: "Bio-Produkte und Lebensmittel",
          fr: "Produits biologiques et alimentaires",
          ar: "منتجات عضوية وأطعمة",
        },
        quick_delivery_title: {
          en: "Quick Delivery to Your Home",
          de: "Schnelle Lieferung zu Ihnen nach Hause",
          fr: "Livraison rapide à votre domicile",
          ar: "توصيل سريع إلى منزلك",
        },
        quick_delivery_description: {
          en: "There are many products you will find in our shop, Choose your daily necessary product from our ZAPMarketplace shop and get some special offers. See Our latest discounted products from here and get a special discount.",
          de: "Es gibt viele Produkte, die Sie in unserem Shop finden. Wählen Sie Ihr täglich benötigtes Produkt aus unserem ZAPMarketplace-Shop und erhalten Sie einige Sonderangebote. Sehen Sie sich hier unsere neuesten reduzierten Produkte an und sichern Sie sich einen Sonderrabatt.",
          fr: "Vous trouverez de nombreux produits dans notre magasin. Choisissez votre produit nécessaire quotidien dans notre magasin ZAPMarketplace et profitez de quelques offres spéciales. Découvrez nos derniers produits en promotion ici et bénéficiez d'une réduction spéciale.",
          ar: "هناك العديد من المنتجات التي ستجدها في متجرنا. اختر منتجك الضروري اليومي من متجر ZAPMarketplace الخاص بنا واحصل على بعض العروض الخاصة. انظر إلى منتجاتنا المخفضة الأحدث من هنا واحصل على خصم خاص.",
        },
        quick_delivery_button: {
          en: "Download App",
          de: "Lade App herunter",
          fr: "Télécharger l'application",
          ar: "تحميل التطبيق",
        },
        quick_delivery_link: "#",
        quick_delivery_img: "https://res.cloudinary.com/ahossain/image/upload/v1697688032/settings/delivery-boy_rluuoq.webp",
        latest_discount_title: {
          en: "Latest Discounted Products",
          de: "Neueste reduzierte Produkte",
          fr: "Derniers produits en promotion",
          ar: "أحدث منتجات بخصم",
        },
        latest_discount_description: {
          en: "See Our latest discounted products below. Choose your daily needs from here and get a special discount with free shipping.",
          de: "Sehen Sie sich unten unsere neuesten reduzierten Produkte an. Wählen Sie hier Ihren täglichen Bedarf und erhalten Sie einen Sonderrabatt mit kostenlosem Versand.",
          fr: "Découvrez nos derniers produits en promotion ci-dessous. Choisissez vos besoins quotidiens à partir d'ici et bénéficiez d'une réduction spéciale avec livraison gratuite.",
          ar: "انظر إلى منتجاتنا المخفضة الأحدث أدناه. اختر احتياجاتك اليومية من هنا واحصل على خصم خاص مع الشحن المجاني.",
        },
        latest_discount_product_limit: 18,
        daily_need_title: {
          en: "Get Your Daily Needs From Our ZAPMarketplace Store",
          de: "Holen Sie sich Ihren täglichen Bedarf in Ihrem CloudCleaver-Shop",
          fr: "Obtenez vos besoins quotidiens dans notre magasin ZAPMarketplace",
          ar: "احصل على احتياجاتك اليومية من متجرنا ZAPMarketplace",
        },
        daily_need_description: {
          en: "There are many products you will find in our shop, Choose your daily necessary product from our ZAPMarketplace shop and get some special offers.",
          de: "Es gibt viele Produkte, die Sie in unserem Shop finden. Wählen Sie Ihr täglich benötigtes Produkt aus unserem ZAPMarketplace-Shop und erhalten Sie einige Sonderangebote.",
          fr: "Vous trouverez de nombreux produits dans notre magasin. Choisissez vos produits nécessaires quotidiens dans notre magasin ZAPMarketplace et bénéficiez de quelques offres spéciales.",
          ar: "هناك العديد من المنتجات التي ستجدها في متجرنا. اختر منتجك الضروري اليومي من متجرنا ZAPMarketplace واحصل على بعض العروض الخاصة.",
        },
        daily_need_app_link: "https://www.apple.com/app-store/",
        daily_need_google_link:
          "https://play.google.com/store/games?utm_source=apac_med&utm_medium=hasem&utm_content=Jun0122&utm_campaign=Evergreen&pcampaignid=MKT-EDR-apac-lk-1003227-med-hasem-py-Evergreen-Jun0122-Text_Search_BKWS-BKWS%7CONSEM_kwid_43700071429441653_creativeid_600975795576_device_c&gclid=CjwKCAjwwo-WBhAMEiwAV4dybdy60tnQqCSnQ-cXShNnEcxmaBx2I6iwwc_WEqoA5sN9YSLJEXh9fBoC3u4QAvD_BwE&gclsrc=aw.ds",
        daily_need_img_left: "https://res.cloudinary.com/ahossain/image/upload/v1697688091/settings/app-download-img-left_s5n2zf.webp",
        daily_need_img_right: "https://res.cloudinary.com/ahossain/image/upload/v1697688091/settings/app-download-img_c7xqg4.webp",
        button1_img: "https://res.cloudinary.com/ahossain/image/upload/v1697688165/settings/app-store_cyyc0f.svg",
        button2_img: "https://res.cloudinary.com/ahossain/image/upload/v1697688167/settings/play-store_cavwua.svg",
      },
      about_us: {
        header_status: true,
        content_left_status: true,
        content_right_status: true,
        content_middle_status: true,
        founder_status: true,
        header_bg: "https://res.cloudinary.com/ahossain/image/upload/v1697439245/settings/yw3cd2xupqwqpqcbxv9l.jpg",
        content_right_img: "https://res.cloudinary.com/ahossain/image/upload/v1697439245/settings/v7g6gowiju0wanpwx70f.jpg",
        content_middle_Img: "https://res.cloudinary.com/ahossain/image/upload/v1697439195/settings/sl8vzvzm54jgzq6sphn2.jpg",
        founder_one_img: "https://res.cloudinary.com/ahossain/image/upload/v1697439688/settings/team-1_acjmv7.webp",
        founder_two_img: "https://res.cloudinary.com/ahossain/image/upload/v1697439689/settings/team-2_dw7zs1.webp",
        founder_three_img: "https://res.cloudinary.com/ahossain/image/upload/v1697439689/settings/team-3_ld3323.webp",
        founder_four_img: "https://res.cloudinary.com/ahossain/image/upload/v1697439689/settings/team-4_i7jvx7.webp",
        founder_five_img: "https://res.cloudinary.com/ahossain/image/upload/v1697439689/settings/team-5_ylyklw.webp",
        founder_six_img: "https://res.cloudinary.com/ahossain/image/upload/v1697439689/settings/team-6_gmlts4.webp",
        title: {
          en: "About Us",
          de: "Über uns",
          fr: "À propos de nous",
          ar: "من نحن",
        },
        top_title: {
          en: "Welcome to our ZAPMarketplace shop",
          de: "Willkommen in unserem ZAPMarketplace-Shop",
          fr: "Bienvenue dans notre magasin ZAPMarketplace",
          ar: "مرحبًا في متجرنا ZAPMarketplace",
        },
        top_description: {
          en: "Holisticly seize parallel metrics and functional ROI.Seamlessly revolutionize error-free internal or organic sources before effective scenarios. Progressively incentivize state of the art applications for efficient intellectual capital. Credibly leverage existing distinctive mindshare through cutting-edge schemas. Proactively procrastinate team building paradigms coordinate client-centric total transparent internal. Dynamically embrace diverse customer service and installed base paradigms. Credibly seize enterprise-wide experiences for end-to-end data. Professionally brand flexible alignments and cost effective architectures. Enthusiastically incentivize seamless communities with seamlessly facilitate revolutionary metrics with strategic theme areas.",
          de: "Erfassen Sie parallele Metriken und funktionalen ROI ganzheitlich. Revolutionieren Sie nahtlos fehlerfreie interne oder organische Quellen vor effektiven Szenarien. Fördern Sie nach und nach hochmoderne Anwendungen für effizientes intellektuelles Kapital. Nutzen Sie glaubwürdig vorhandenes unverwechselbares Mindshare durch hochmoderne Schemata. Teambuilding-Paradigmen proaktiv aufschieben koordinieren kundenzentriert total transparent intern. Umfassen Sie dynamisch unterschiedliche Kundendienst- und Installed-Base-Paradigmen. Nutzen Sie glaubwürdig unternehmensweite Erfahrungen für End-to-End-Daten. Professionelles Branding flexibler Ausrichtungen und kostengünstiger Architekturen. Schaffen Sie enthusiastische Anreize für nahtlose Gemeinschaften, indem Sie revolutionäre Metriken mit strategischen Themenbereichen nahtlos erleichtern.",
          fr: "Saisissez de manière holistique des métriques parallèles et un ROI fonctionnel. Révolutionnez sans heurts les sources internes ou organiques sans erreur avant des scénarios efficaces. Incentivez progressivement les applications de pointe pour un capital intellectuel efficace. Exploitez de manière crédible le partage d'esprit distinctif existant grâce à des schémas de pointe. Procrastinez de manière proactive les paradigmes de construction d'équipe, coordonnez de manière centrée sur le client une transparence totale interne. Embrassez de manière dynamique divers paradigmes de service client et de base installée. Saisissez de manière crédible des expériences à l'échelle de l'entreprise pour des données de bout en bout. Marquez de manière professionnelle des alignements flexibles et des architectures rentables. Incentivez avec enthousiasme des communautés sans couture en facilitant de manière transparente des métriques révolutionnaires avec des thèmes stratégiques.",
          ar: "التقاط بشكل شامل مقاييس موازية وعائد استثماري وظيفي. ثورة بسلاسة في مصادر داخلية أو عضوية خالية من الأخطاء قبل السيناريوهات الفعالة. حافز تدريجياً على تطبيقات حديثة لرأس المال الفكري الكفء. استفد من مشاركة الأفكار المميزة القائمة بالفعل من خلال مخططات حديثة. قم بتأجيل تنظيم أنماط بناء الفريق بشكل نشط وتنسيق الشفافية التامة الخاصة بالعميل داخليًا. اعتنق بنشاط خدمة العملاء المتنوعة والأسس المثبتة. استفد بشكل موثوق من تجارب تغطيتها الشركة بالكامل للبيانات من البداية إلى النهاية. قم بتسويق العلامة بشكل احترافي لتوجيهات مرنة وهندسات تكلفة فعّالة. حفز بحماس المجتمعات السلسة وسهل تيسير المقاييس الثورية مع المناطق الاستراتيجية.",
        },
        card_one_title: {
          en: "10K",
          de: "10K",
          fr: "10K",
          ar: "10 ألف",
        },
        card_one_sub: {
          en: "Listed Products",
          de: "Gelistete Produkte",
          fr: "Produits répertoriés",
          ar: "منتجات مدرجة",
        },
        card_one_description: {
          en: "Dynamically morph team driven partnerships after vertical",
          de: "Verwandeln Sie teamorientierte Partnerschaften dynamisch nach der Vertikalen",
          fr: "Métamorphose dynamique des partenariats axés sur l'équipe après la verticalisation",
          ar: "تحول دينامي للشراكات الموجهة من قبل الفريق بعد التمييز",
        },
        card_two_title: {
          en: "8K",
          de: "8 TAUSEND",
          fr: "8K",
          ar: "8 ألف",
        },
        card_two_sub: {
          en: "Lovely Customer",
          de: "Lieber Kunde",
          fr: "Clients adorables",
          ar: "زبائن رائعين",
        },
        card_two_description: {
          en: "Competently productize virtual models without performance.",
          de: "Virtuelle Modelle ohne Performance kompetent produzieren.",
          fr: "Produire compétemment des modèles virtuels sans performance.",
          ar: "تصنيع نماذج افتراضية بكفاءة دون أداء.",
        },
        middle_description_one: {
          en: "Holisticly seize parallel metrics and functional ROI. Seamlessly revolutionize error-free internal or organic sources before effective scenarios. Progressively incentivize state of the art applications for efficient intellectual capital. Credibly leverage existing distinctive mindshare through cutting-edge schemas. Proactively procrastinate team building paradigms coordinate client-centric total transparent internal. Energistically reconceptualize global leadership for high-quality networks. Credibly restore an expanded array of systems rather than accurate results. Collaboratively synergize backend bandwidth without 24/7 functionalities. Credibly utilize proactive ideas whereas cross-media core competencies. Uniquely maximize professional best practices through resource maximizing services. Conveniently architect cross-unit web services for e-business imperatives.",
          de: "Erfassen Sie parallele Metriken und funktionalen ROI ganzheitlich. Revolutionieren Sie nahtlos fehlerfreie interne oder organische Quellen vor effektiven Szenarien. Fördern Sie nach und nach hochmoderne Anwendungen für effizientes intellektuelles Kapital. Nutzen Sie glaubwürdig vorhandenes unverwechselbares Mindshare durch hochmoderne Schemata. Teambuilding-Paradigmen proaktiv aufschieben koordinieren kundenzentriert total transparent intern. Globale Führung für qualitativ hochwertige Netzwerke energisch neu konzipieren. Stellen Sie statt genauer Ergebnisse eine größere Anzahl von Systemen glaubwürdig wieder her. Synergisieren Sie gemeinsam Backend-Bandbreite ohne 24/7-Funktionalitäten. Proaktive Ideen glaubhaft nutzen und crossmediale Kernkompetenzen nutzen. Maximieren Sie auf einzigartige Weise professionelle Best Practices durch ressourcenoptimierende Services. Entwickeln Sie bequem bereichsübergreifende Webservices für E-Business-Anforderungen.",
          fr: "Saisissez de manière holistique des métriques parallèles et un ROI fonctionnel. Révolutionnez sans heurts les sources internes ou organiques sans erreur avant des scénarios efficaces. Incentivez progressivement les applications de pointe pour un capital intellectuel efficace. Exploitez de manière crédible le partage d'esprit distinctif existant grâce à des schémas de pointe. Procrastinez de manière proactive les paradigmes de construction d'équipe, coordonnez de manière centrée sur le client une transparence totale interne. Reconcevez de manière énergique un leadership mondial pour des réseaux de haute qualité. Restaurez de manière crédible un large éventail de systèmes plutôt que des résultats précis. Synergiez de manière collaborative la bande passante de l'infrastructure sans fonctionnalités 24/7. Utilisez de manière crédible des idées proactives tout en exploitant des compétences de base cross-media. Maximisez de manière unique les meilleures pratiques professionnelles grâce à des services de maximisation des ressources. Concevez commodément des services Web inter-unités pour les impératifs de l'e-commerce.",
          ar: "التقاط بشكل شامل مقاييس موازية وعائد استثماري وظيفي. ثورة بسلاسة في مصادر داخلية أو عضوية خالية من الأخطاء قبل السيناريوهات الفعالة. حافز تدريجياً على تطبيقات حديثة لرأس المال الفكري الكفء. استفد من مشاركة الأفكار المميزة القائمة بالفعل من خلال مخططات حديثة. قم بتأجيل تنظيم أنماط بناء الفريق بشكل نشط وتنسيق الشفافية التامة الخاصة بالعميل داخليًا. إعادة تصوير القيادة العالمية بشكل نشط لشبكات عالية الجودة بحماس. استعادة مجموعة موسعة من الأنظمة بشكل موثوق بدلاً من النتائج الدقيقة. تعاون بشكل تنسيقي على تواصل خلفية البنية التحتية دون وجود وظائف على مدار الساعة طوال أيام الأسبوع. استفد بشكل موثوق من الأفكار الاستباقية بينما تستخدم الكفاءات الأساسية عبر وسائط الإعلام المتعددة. زيادة الاستفادة بشكل فريد من أفضل الممارسات المهنية من خلال خدمات تحسين الاستفادة من الموارد. صمم بشكل ملائم خدمات الويب بين الوحدات المتقاطعة لمتطلبات التجارة الإلكترونية.",
        },

        middle_description_two: {
          en: "Appropriately visualize market-driven data before one-to-one scenarios. Collaboratively productize multifunctional ROI through intuitive supply chains. Enthusiastically seize revolutionary value and process-centric services. Competently harness intuitive information after interoperable markets. Interactively revolutionize future-proof value before granular sources. Dynamically embrace diverse customer service and installed base paradigms. Credibly seize enterprise-wide experiences for end-to-end data. Professionally brand flexible alignments and cost-effective architectures. Enthusiastically incentivize seamless communities with seamlessly facilitate revolutionary metrics with strategic theme areas.",
          de: "Visualisieren Sie marktgesteuerte Daten angemessen vor Eins-zu-eins-Szenarien. Erzielen Sie gemeinsam multifunktionale Renditen durch intuitive Lieferketten. Nutzen Sie mit Begeisterung revolutionäre Mehrwert- und prozessorientierte Services. Nutzen Sie intuitive Informationen kompetent nach interoperablen Märkten. Revolutionieren Sie interaktiv zukunftssichere Werte vor granularen Quellen. Umfassen Sie dynamisch unterschiedliche Kundendienst- und Installed-Base-Paradigmen. Nutzen Sie glaubwürdig unternehmensweite Erfahrungen für End-to-End-Daten. Professionelles Branding flexibler Ausrichtungen und kostengünstiger Architekturen. Schaffen Sie enthusiastische Anreize für nahtlose Gemeinschaften, indem Sie revolutionäre Metriken mit strategischen Themenbereichen nahtlos erleichtern.",
          fr: "Visualisez de manière appropriée des données axées sur le marché avant les scénarios en tête-à-tête. Produisez en collaboration un ROI multifonctionnel grâce à des chaînes d'approvisionnement intuitives. Saisissez avec enthousiasme une valeur révolutionnaire et des services axés sur les processus. Exploitez de manière compétente des informations intuitives après les marchés interopérables. Révolutionnez de manière interactive une valeur à l'épreuve du futur avant les sources granulaires. Embrassez de manière dynamique les paradigmes de service client variés et de base installée. Saisissez de manière crédible des expériences à l'échelle de l'entreprise pour des données de bout en bout. Marquez professionnellement des alignements flexibles et des architectures rentables. Incitez avec enthousiasme les communautés sans couture à faciliter de manière transparente des métriques révolutionnaires avec des thèmes stratégiques.",
          ar: "قم بتصوير البيانات المدفوعة بالسوق بشكل مناسب قبل سيناريوهات مباشرة. قم بإنتاج عائد استثمار متعدد الوظائف بالتعاون من خلال سلاسل الإمداد البديهية. استفد بحماسة من القيمة الثورية والخدمات الموجهة نحو العمليات. استغل المعلومات البديهية بكفاءة بعد الأسواق التوافقية. قم بثورة تفاعلية فيما يتعلق بالقيمة المضمونة مستقبلياً قبل المصادر المفصلة. اعتنق بنشاط خدمة العملاء المتنوعة والنماذج المثبتة. استفد بمصداقية من تجارب عملية على مستوى الشركة للبيانات من البداية إلى النهاية. قم بتسويق الموازنات المرنة والهندسات التكلفية الفعالة بشكل محترف. حفز بحماس المجتمعات السلسة وقدم بسلاسة مؤشرات ثورية مع مناطق ذات موضوع استراتيجي.",
        },
        founder_title: {
          en: "Our Team",
          de: "Unser Gründer",
          fr: "Notre équipe",
          ar: "فريقنا",
        },
        founder_description: {
          en: "We’re impartial and independent, and every day we create distinctive, world-class reintermediate backend supply programmes...",
          de: "Wir sind unparteiisch und unabhängig und erstellen jeden Tag unverwechselbare, erstklassige Reintermediate-Backend-Lieferprogramme...",
          fr: "Nous sommes impartiaux et indépendants, et chaque jour nous créons des programmes distinctifs de réintermédiation de l'approvisionnement en backend de classe mondiale...",
          ar: "نحن نتحلى بالنزاهة والاستقلالية، ونقوم يومياً بإنشاء برامج توريد الخلفية المميزة والعالمية...",
        },
        founder_one_name: {
          en: "Niamh Shea",
          de: "Niamh Shea",
          fr: "Niamh Shea",
          ar: "نيامه شيا",
        },
        founder_one_sub: {
          en: "Co-founder & Executive",
          de: "Co-founder & Executive",
          fr: "Co-fondateur & Directeur",
          ar: "مؤسس مشارك وتنفيذي",
        },
        founder_two_name: {
          en: "Orla Dwyer",
          de: "Orla Dwyer",
          fr: "Orla Dwyer",
          ar: "أورلا دواير",
        },
        founder_two_sub: {
          en: "Orla Dwyer",
          de: "Orla Dwyer",
          fr: "Orla Dwyer",
          ar: "أورلا دواير",
        },
        founder_three_name: {
          en: "Danien James",
          de: "Danien James",
          fr: "Danien James",
          ar: "دانين جيمس",
        },
        founder_three_sub: {
          en: "Co-founder, Chairman",
          de: "Co-founder, Chairman",
          fr: "Co-fondateur, Président",
          ar: "مؤسس مشارك، رئيس مجلس الإدارة",
        },
        founder_four_name: {
          en: "Dara Frazier",
          de: "Dara Frazier",
          fr: "Dara Frazier",
          ar: "دارا فريزر",
        },
        founder_four_sub: {
          en: "Chief Strategy Officer",
          de: "Chief Strategy Officer",
          fr: "Directeur de la stratégie en chef",
          ar: "مدير استراتيجي رئيسي",
        },
        founder_five_name: {
          en: "Glenda Arvidson",
          de: "Glenda Arvidson",
          fr: "Glenda Arvidson",
          ar: "غليندا أرفيدسون",
        },
        founder_five_sub: {
          en: "HR Officer",
          de: "HR Officer",
          fr: "Responsable des ressources humaines",
          ar: "مسؤول الموارد البشرية",
        },
        founder_six_name: {
          en: "Melvin Davis",
          de: "Melvin Davis",
          fr: "Melvin Davis",
          ar: "ميلفين ديفيس",
        },
        founder_six_sub: {
          en: "Lead Developer",
          de: "Lead Developer",
          fr: "Développeur principal",
          ar: "مطور رئيسي",
        },
      },
      contact_us: {
        header_status: true,
        email_box_status: true,
        call_box_status: true,
        address_box_status: true,
        left_col_status: true,
        form_status: true,
        header_bg: "https://res.cloudinary.com/ahossain/image/upload/v1697439245/settings/yw3cd2xupqwqpqcbxv9l.jpg",
        left_col_img: "https://res.cloudinary.com/ahossain/image/upload/v1697472924/settings/contact-us_zvwn2n.png",

        title: {
          en: "Contact Us",
          de: "Kontaktiere uns",
          fr: "Contactez-nous",
          ar: "اتصل بنا",
        },
        email_box_title: {
          en: "Email Us",
          de: "Schreiben Sie uns eine E-Mail",
          fr: "Envoyez-nous un e-mail",
          ar: "أرسل لنا بريدًا إلكترونيًا",
        },
        email_box_email: {
          en: "info@zapmarketplace.com",
          de: "info@zapmarketplace.com",
          fr: "info@zapmarketplace.com",
          ar: "info@zapmarketplace.com",
        },
        email_box_text: {
          en: "Interactively grow empowered for process-centric total linkage.",
          de: "Wachsen Sie interaktiv und stärken Sie die prozessorientierte Gesamtvernetzung.",
          fr: "Grandissez de manière interactive et renforcez la liaison totale centrée sur le processus.",
          ar: "نمو تفاعلي لزيادة التمكين للربط الشامل تحت العمليات.",
        },
        call_box_title: {
          en: "Call Us",
          de: "Rufen Sie uns an",
          fr: "Appelez-nous",
          ar: "اتصل بنا",
        },
        call_box_phone: {
          en: "029-00124667",
          de: "029-00124667",
          fr: "029-00124667",
          ar: "029-00124667",
        },
        call_box_text: {
          en: "Distinctively disseminate focused solutions clicks-and-mortar ministate.",
          de: "Unterscheidbar Lösungen fokussiert verbreiten Klicks-und-Mörtel Ministaat.",
          fr: "Diffuser distinctivement des solutions ciblées pour un État ministériel à clics et à mortier.",
          ar: "نشر حلاً مميزًا موجهًا للحكومة والمقررات ذات النقر والأسمنت.",
        },
        address_box_title: {
          en: "Location",
          de: "Ort",
          fr: "Emplacement",
          ar: "الموقع",
        },
        address_box_address_one: {
          en: "Boho One, Bridge Street West, Middlesbrough, North Yorkshire, TS2 1AE.",
          de: "Boho One, Bridge Street West, Middlesbrough, North Yorkshire, TS2 1AE.",
          fr: "Boho One, Bridge Street West, Middlesbrough, North Yorkshire, TS2 1AE.",
          ar: "Boho One, Bridge Street West, Middlesbrough, North Yorkshire, TS2 1AE.",
        },
        address_box_address_two: {
          en: "561-4535 Nulla LA",
          de: "561-4535 Nulla LA",
          fr: "561-4535 Nulla LA",
          ar: "561-4535 Nulla LA",
        },
        address_box_address_three: {
          en: "United States 96522.",
          de: "United States 96522",
          fr: "États-Unis 96522.",
          ar: "الولايات المتحدة 96522",
        },
        form_title: {
          en: "For any support just send your query",
          de: "Für Unterstützung senden Sie einfach Ihre Anfrage",
          fr: "Pour tout support, envoyez simplement votre demande",
          ar: "لأي دعم، مجرد إرسال استفسارك",
        },
        form_description: {
          en: "Collaboratively promote client-focused convergence vis-a-vis customer-directed alignments via plagiarized strategic users and standardized infrastructures.",
          de: "Fördern Sie gemeinsam die kundenorientierte Konvergenz gegenüber kundenorientierten Ausrichtungen durch Plagiate strategischer Benutzer und standardisierter Infrastrukturen.",
          fr: "Promouvoir collaborativement la convergence axée sur le client par rapport aux alignements dirigés par le client via des utilisateurs stratégiques plagiés et des infrastructures standardisées.",
          ar: "تعزيز تحقيق تلاقي توجيه العملاء مقابل توجيه العملاء من خلال المستخدمين الاستراتيجيين المنسوخين والبنى التحتية الموحدة.",
        },
      },
      offers: {
        header_status: true,
        header_bg: "https://res.cloudinary.com/ahossain/image/upload/v1697439245/settings/yw3cd2xupqwqpqcbxv9l.jpg",

        title: {
          en: "Mega Offer",
          de: "Mega Angebot",
          fr: "Méga Offre",
          ar: "عرض ميجا",
        },
        coupon_code: ["SUMMER21", "WINTER21", "AUGUST21", "OCTOBER21"],
      },
      privacy_policy: {
        status: true,
        header_bg: "https://res.cloudinary.com/ahossain/image/upload/v1697439245/settings/yw3cd2xupqwqpqcbxv9l.jpg",
        title: {
          en: "Privacy Policy",
          de: "Datenschutz-Bestimmungen",
          fr: "Politique de confidentialité",
          ar: "سياسة الخصوصية",
        },
        description: {
          en: "<h1><strong>Last updated: February 15, 2022</strong></h1>\n<p>At ZAPMarketplace, accessible from zapmarketplace dot com, one of our main priorities is the privacy of our visitors. This Privacy Policy document contains types of information that is collected and recorded by ZAPMarketplace and how we use it. If you have additional questions or require more information about our Privacy Policy, do not hesitate to contact us.we may receive additional information about you such as your name, email address, phone number, the contents of the message and/or attachments you may send us, and any other information you may choose to provide. When you register for an Account, we may ask for your contact information, including items such as name, company name, address, email address, and telephone number.</p>\n<p>This Privacy Policy applies only to our online activities and is valid for visitors to our website with regards to the information that they shared and/or collect in ZAPMarketplace.we may receive additional information about you such as your name, email address, phone number, the contents of the message and/or attachments you may send us, we may ask for your contact information, including items such as name, company name, address, email address, and telephone number. This policy is not applicable to any information collected offline or via channels other than this website. Our Privacy Policy was created with the help of the Free Privacy Policy Generator.</p>\n<h1><strong>Consent</strong></h1>\n<p>By using our website, you hereby consent to our Privacy Policy and agree to its terms.</p>\n<h1><strong>Information we collect</strong></h1>\n<p>The personal information that you are asked to provide, and the reasons why you are asked to provide it, will be made clear to you at the point we ask you to provide your personal information. If you contact us directly, we may receive additional information about you such may choose to provide. When you register for an Account, we may ask for your contact information, including items such as name, company name, address, email address, and telephone number.</p>\n<p>Please note that the Company will not ask you to share any sensitive data or information via email or telephone. If you receive any such request by email or telephone, please do not respond/divulge any sensitive data or information and forward the information relating to the same to</p>\n<h1><strong>How we use your information</strong></h1>\n<p>We use the information we collect in various ways, including to:</p>\n<ol>\n<li>1. Provide, operate, and maintain our website, to provide you with updates and other information.</li>\n<li>2. Improve, personalize, and expand our website,and other information relating to the website.</li>\n<li>3. Understand and analyze how you use our website, to provide you with updates and other information relating to the website.</li>\n<li>4. Develop new products, services, features, and functionality,and other information relating to the website.</li>\n<li>5. Communicate with you, either directly or through one of our partners, including for customer service, to provide you with updates.</li>\n<li>6. Send you emails. To provide you with updates and other information relating to the website, and for marketing and promotional purposes</li>\n<li>7. Find and prevent fraud. To provide you with updates and other information relating to the website, and for marketing and promotional purposes</li>\n</ol>\n<h1><strong>Log Files</strong></h1>\n<p>ZAPMarketplace follows a standard procedure of using log files. These files log visitors when they visit websites. All hosting companies do this and a part of hosting. The information collected by log files include internet protocol (IP) addresses, browser type, Internet Service Provider (ISP), date and time stamp, referring/exit pages, and possibly the number of clicks. These are not linked to any information that is personally identifiable. The purpose of the information is for analyzing trends, administering the site, tracking users' movement on the website, and gathering demographic information.</p>\n<h1><strong>Advertising Partners Privacy Policies</strong></h1>\n<p>You may consult this list to find the Privacy Policy for each of the advertising partners of ZAPMarketplace. Third-party ad servers or ad networks uses technologies like cookies, JavaScript, or Web Beacons that are used in their respective advertisements and links that appear on ZAPMarketplace, which are sent directly to users' browser. They automatically receive your IP address when this occurs. These technologies are used to measure the effectiveness of their advertising campaigns and/or to personalize the advertising content that you see on websites that you visit. Note that ZAPMarketplace has no access to or control over these cookies that are used by third-party advertisers.</p>\n<h1><strong>Third Party Privacy Policies</strong></h1>\n<p>Third-party ad servers or ad networks uses technologies like cookies, JavaScript, or Web Beacons that are used in their respective advertisements and links that appear on ZAPMarketplace, which are sent directly to users' browser. They automatically receive your IP address when this occurs. These technologies are used to measure the effectiveness of their advertising campaigns and/or to personalize the advertising content that you see on websites that you visit. Note that ZAPMarketplace has no access to or control over these cookies that are used by third-party advertisers.</p>\n<p>ZAPMarketplace's Privacy Policy does not apply to other advertisers or websites. Thus, we are advising you to consult the respective Privacy Policies of these third-party ad servers for more detailed information. It may include their practices and instructions about how to opt-out of certain options. You can choose to disable cookies through your individual browser options. To know more detailed information about cookie management with specific web browsers, it can be found at the browsers' respective websites.</p>\n<h1><strong>CCPA Privacy Rights</strong></h1>\n<p>Under the CCPA, among other rights, California consumers have the right to: Request that a business that collects a consumer's personal data disclose the categories and specific pieces of personal data that a business has collected about consumers. Request that a business delete any personal data about the consumer that a business has collected. Request that a business that sells a consumer's personal data, not sell the consumer's personal data. If you make a request, we have one month to respond to you. If you would like to exercise any of these rights, please contact us.</p>\n<h1><strong>Children's Information</strong></h1>\n<p>Another part of our priority is adding protection for children while using the internet. We encourage parents and guardians to observe, participate in, and/or monitor and guide their online activity.Request that a business delete any personal data about the consumer that a business has collected. If you make a request, we have one month to respond to you. If you would like to exercise any of these rights, please contact us.</p>\n<p>ZAPMarketplace does not knowingly collect any Personal Identifiable Information from children under the age of 13. If you think that your child provided this kind of information on our website, we strongly encourage you to contact us immediately and we will do our best efforts to promptly remove such information from our records.</p>\n",
        },
      },
      term_and_condition: {
        status: true,
        header_bg: "https://res.cloudinary.com/ahossain/image/upload/v1697439245/settings/yw3cd2xupqwqpqcbxv9l.jpg",
        title: {
          en: "Terms & Conditions",
          de: "Terms & Bedingungen",
          fr: "Termes et conditions",
          ar: "الشروط والأحكام",
        },
        description: {
          en: '<h1><strong>Welcome to ZAPMarketplace!</strong></h1>\n<p>These terms and conditions outline the rules and regulations for the use of ZAPMarketplace\'s Website, located at https://zapmarketplace.com/. By accessing this website we assume you accept these terms and conditions. Do not continue to use ZAPMarketplace if you do not agree to take all of the terms and conditions stated on this page.</p>\n<p>The following terminology applies to these Terms and Conditions, Privacy Statement and Disclaimer Notice and all Agreements: Client, You and Your refers to you, the person log on this website and compliant to the Company’s terms and conditions. The Company, refers to our CompanyPartParties or Us refers to both the Client and ourselves. All terms refer to the offer, acceptance and consideration of payment necessary to undertake the process of our assistance to the Client in the most appropriate manner for the express purpose of meeting the Client’s needs in respect of provision of the Company’s stated services, in accordance with and subject to, prevailing law of Netherlands. Any use of the above terminology or other words in the singular, plural, capitalization and/or he/she or they, are taken as interchangeable and therefore as referring to same.</p>\n<h1><strong>Cookies</strong></h1>\n<p>We employ the use of cookies. By accessing ZAPMarketplace, you agreed to use cookies in agreement with the ZAPMarketplace\'s Privacy Policy. Most interactive websites use cookies to let us retrieve the user’s details for each visit. Cookies are used by our website to enable the functionality of certain areas to make it easier for people visiting our website. Some of our affiliate/advertising partners may also use cookies.</p>\n<h1><strong>License</strong></h1>\n<p>Unless otherwise stated, ZAPMarketplace and/or its licensors own the intellectual property rights for all material on ZAPMarketplace. All intellectual property rights are reserved. You may access this from ZAPMarketplace for your own personal use subjected to restrictions set in these terms and conditions.This Agreement shall begin on the date hereof. Our Terms and Conditions were created with the help of the Terms And Conditions Generator.<strong>You must not:</strong></p>\n<ul>\n<li>1. Identifiers (e.g. name, mailing address, email address, phone number, credit/debit card number)</li>\n<li>2. Characteristics of protected classifications (e.g. gender, age)</li>\n<li>3. Commercial information (e.g. products or services purchased, purchase history)</li>\n<li>4. Internet or other electronic network activity (e.g. browse or search history)</li>\n<li>5. Geo location data (e.g. latitude or longitude)</li>\n<li>6. Audio, electronic, visual, or similar information (e.g. recording of Guest service calls)</li>\n<li>7. Inferences drawn from any of the above (e.g. preferences or characteristics)</li>\n</ul>\n<p>Parts of this website offer an opportunity for users to post and exchange opinions and information in certain areas of the website. ZAPMarketplace does not filter, edit, publish or review Comments prior to their presence on the website. Comments do not reflect the views and opinions of ZAPMarketplace,its agents and/or affiliates. Comments reflect the views and opinions of the person who post their views and opinions. To the extent permitted by applicable laws, ZAPMarketplace shall not be liable for the Comments or for any liability, damages or expenses caused and/or suffered as a result of any use of and/or posting of and/or appearance of the Comments on this website.</p>\n<h1><strong>Content Liability</strong></h1>\n<p>We shall not be hold responsible for any content that appears on your Website. You agree to protect and defend us against all claims that is rising on your Website. No link(s) should appear on any Website that may be interpreted as libelous, obscene or criminal, or which infringes, otherwise violates, or advocates the infringement or other violation of, any third party rights.Without prior approval and written permission, you may not create frames around our Webpages that alter in any way the visual presentation or appearance of our Website.</p>\n<h1><strong>Your Privacy</strong></h1>\n<p>Please read <a href="https://store.zapmarketplace.online/privacy-policy" target="_self">Privacy Policy</a></p>\n<h1><strong>Reservation of Rights</strong></h1>\n<p>We reserve the right to request that you remove all links or any particular link to our Website. You approve to immediately remove all links to our Website upon request. We also reserve the right to amen these terms and conditions and it’s linking policy at any time. By continuously linking to our Website, you agree to be bound to and follow these linking terms and conditions.</p>\n<h1><strong>Disclaimer</strong></h1>\n<p>To the maximum extent permitted by applicable law, we exclude all representations, warranties and conditions relating to our website and the use of this website. Nothing in this disclaimer will:</p>\n<ul>\n<li>1. limit or exclude our or your liability for death or personal injury;</li>\n<li>2. limit or exclude our or your liability for fraud or fraudulent misrepresentation;</li>\n<li>3. limit any of our or your liabilities in any way that is not permitted under applicable law; or</li>\n<li>4. exclude any of our or your liabilities that may not be excluded under applicable law.</li>\n</ul>\n<p>The limitations and prohibitions of liability set in this Section and elsewhere in this disclaimer: (a) are subject to the preceding paragraph; and (b) govern all liabilities arising under the disclaimer, including liabilities arising in contract, in tort and for breach of statutory duty. As long as the website and the information and services on the website are provided free of charge, we will not be liable for any loss or damage of any nature.</p>\n',
        },
      },
      faq: {
        page_status: true,
        leftcol_status: true,
        rightcol_status: true,
        header_bg: "https://res.cloudinary.com/ahossain/image/upload/v1697439245/settings/yw3cd2xupqwqpqcbxv9l.jpg",
        left_img: "https://res.cloudinary.com/ahossain/image/upload/v1697687955/settings/faq_qr1y1h.svg",
        title: {
          en: "FAQs",
          de: "Häufig gestellte Fragen",
          fr: "FAQ",
          ar: "الأسئلة الشائعة",
        },
        faq_one: {
          en: "How does the ZAPMarketplace work?",
          de: "Wie funktioniert der ZAPMarketplace?",
          fr: "Comment fonctionne ZAPMarketplace ?",
          ar: "كيف يعمل ZAPMarketplace؟",
        },
        description_one: {
          en: "Distinctively initiate error-free channels with highly efficient ROI. Intrinsicly envisioneer world-class data via best-of-breed best practices. Efficiently enable empowered e-tailers after cross-unit services. Uniquely expedite seamless e-tailers via cooperative interfaces. Monotonectally myocardinate customer directed meta-services whereas error-free scenarios.",
          de: "Initiieren Sie gezielt fehlerfreie Kanäle mit hocheffizientem ROI. Stellen Sie sich durch branchenführende Best Practices erstklassige Daten vor. Ermöglichen Sie leistungsstarken E-Händlern auf effiziente Weise die Bereitstellung abteilungsübergreifender Dienstleistungen. Beschleunigen Sie nahtlose E-Tailer auf einzigartige Weise über kooperative Schnittstellen. Monotone myokardinierte kundengesteuerte Metadienste während fehlerfreier Szenarien.",
          fr: "Initiez distinctement des canaux sans erreur avec un retour sur investissement très efficace. Envisionnez intrinsèquement des données de classe mondiale via les meilleures pratiques. Activez efficacement les e-commerçants autonomes après des services inter-unités. Expédiez de manière unique des e-commerçants sans problème via des interfaces coopératives. Myocardinate monotonement les métaservices dirigés par le client dans des scénarios sans erreur.",
          ar: "بدء قنوات خالية من الأخطاء بتأثير عالي للاستثمار. تصور البيانات عالمية المستوى من خلال أفضل الممارسات. تمكين التجار الإلكتروني الممكنين بفعالية بعد الخدمات بين الوحدات. تسهيل تسليس فريد للتجار الإلكتروني عبر واجهات تعاونية. توجيه الميتا-خدمات الموجهة نحو العملاء بشكل منتظم في سيناريوهات خالية من الأخطاء.",
        },
        faq_two: {
          en: "Can I cancel my subscription anytime?",
          de: "Kann ich mein Abonnement jederzeit kündigen?",
          fr: "Puis-je annuler mon abonnement à tout moment ?",
          ar: "هل يمكنني إلغاء اشتراكي في أي وقت؟",
        },
        description_two: {
          en: "Distinctively initiate error-free channels with highly efficient ROI. Intrinsicly envisioneer world-class data via best-of-breed best practices. Efficiently enable empowered e-tailers after cross-unit services. Uniquely expedite seamless e-tailers via cooperative interfaces. Monotonectally myocardinate customer directed meta-services whereas error-free scenarios.",
          de: "Ja. Sie können Ihr Abonnement jederzeit kündigen. Ihr Abonnement bleibt bis zum Ende Ihrer aktuellen Laufzeit (Monat oder Jahr) aktiv, verlängert sich jedoch nicht automatisch. Sofern Sie Ihr Konto nicht manuell löschen, werden Ihr Konto und alle Daten 60 Tage nach Inaktivität Ihres Abonnements gelöscht.",
          fr: "Initiez distinctement des canaux sans erreur avec un retour sur investissement très efficace. Envisionnez intrinsèquement des données de classe mondiale via les meilleures pratiques. Activez efficacement les e-commerçants autonomes après des services inter-unités. Expédiez de manière unique des e-commerçants sans problème via des interfaces coopératives. Myocardinate monotonement les métaservices dirigés par le client dans des scénarios sans erreur.",
          ar: "بدء قنوات خالية من الأخطاء بتأثير عالي للاستثمار. تصور البيانات عالمية المستوى من خلال أفضل الممارسات. تمكين التجار الإلكتروني الممكنين بفعالية بعد الخدمات بين الوحدات. تسهيل تسليس فريد للتجار الإلكتروني عبر واجهات تعاونية. توجيه الميتا-خدمات الموجهة نحو العملاء بشكل منتظم في سيناريوهات خالية من الأخطاء.",
        },
        faq_three: {
          en: "Whice payment method you should accept?",
          de: "Welche Zahlungsmethode sollten Sie akzeptieren?",
          fr: "Quelle méthode de paiement devriez-vous accepter ?",
          ar: "أي طريقة دفع يجب أن تقبل؟",
        },
        description_three: {
          en: "Holisticly engage sticky niche markets before collaborative collaboration and idea-sharing. Phosfluorescently facilitate parallel applications with unique imperatives. Proactively plagiarize functionalized deliverables via inexpensive solutions. Collaboratively embrace web-enabled infomediaries rather than diverse testing procedures.",
          de: "Ja. Sie können Ihr Abonnement jederzeit kündigen. Ihr Abonnement bleibt bis zum Ende Ihrer aktuellen Laufzeit (Monat oder Jahr) aktiv, verlängert sich jedoch nicht automatisch. Sofern Sie Ihr Konto nicht manuell löschen, werden Ihr Konto und alle Daten 60 Tage nach Inaktivität Ihres Abonnements gelöscht.",
          fr: "Engagez de manière holistique les marchés de niche collants avant la collaboration collaborative et le partage d'idées. Facilitez phosphorescently les applications parallèles avec des impératifs uniques. Plagiez de manière proactive les livrables fonctionnalisés via des solutions peu coûteuses. Embrassez de manière collaborative des infomédiaires activés par le web plutôt que des procédures de test diverses.",
          ar: "شارك بشكل شامل في أسواق الفئة اللزجة قبل التعاون التعاوني وتبادل الأفكار. ساعد في تسهيل التطبيقات الموازية بأهداف فريدة. قم بنسخ النتائج المتخصصة بشكل نشط من خلال حلول ميسرة. اعتماد منهجية تعاونية لاستضافة معلومات الويب بدلاً من إجراءات الاختبار المتنوعة.",
        },
        faq_four: {
          en: "Can I cancel my subscription anytime?",
          de: "Can I cancel my subscription anytime?",
          fr: "Puis-je annuler mon abonnement à tout moment ?",
          ar: "هل يمكنني إلغاء اشتراكي في أي وقت؟",
        },
        description_four: {
          en: "Continually impact seamless imperatives for best-of-breed best practices. Phosfluorescently facilitate parallel applications with unique imperatives. Proactively plagiarize functionalized deliverables via inexpensive solutions. Collaboratively embrace web-enabled infomediaries rather than diverse testing procedures.",
          de: "Continually impact seamless imperatives for best-of-breed\nbest practices. Phosfluorescently facilitate parallel\n                      applications with unique imperatives. Proactively\n                      plagiarize functionalized deliverables via inexpensive\n                      solutions. Collaboratively embrace web-enabled\n                      infomediaries rather than diverse testing procedures.",
          fr: "Impactez continuellement des impératifs sans faille pour les meilleures pratiques. Facilitez phosphorescently les applications parallèles avec des impératifs uniques. Plagiez de manière proactive les livrables fonctionnalisés via des solutions peu coûteuses. Embrassez de manière collaborative des infomédiaires activés par le web plutôt que des procédures de test diverses.",
          ar: "أثر باستمرار على الضرورات السلسة لأفضل الممارسات. ساعد في تيسير التطبيقات الموازية بأهداف فريدة. نسخ النتائج المتخصصة بشكل نشط من خلال حلول ميسرة. اعتماد منهجية تعاونية لاستضافة معلومات الويب بدلاً من إجراءات الاختبار المتنوعة.",
        },
        faq_five: {
          en: "What is ZAPMarketplace EC2 auto scaling?",
          de: "Was ist die automatische Skalierung von ZAPMarketplace EC2?",
          fr: "Qu'est-ce que la mise à l'échelle automatique ZAPMarketplace EC2 ?",
          ar: "ما هو توسيع ZAPMarketplace EC2 التلقائي؟",
        },
        description_five: {
          en: "Continually impact seamless imperatives for best-of-breed best practices. Phosfluorescently facilitate parallel applications with unique imperatives. Proactively plagiarize functionalized deliverables via inexpensive solutions. Collaboratively embrace web-enabled infomediaries rather than diverse testing procedures.",
          de: "Kontinuierliche Umsetzung nahtloser Anforderungen für Best-of-Breed-Best Practices. Phosfluoreszierend erleichtert parallele Anwendungen mit einzigartigen Anforderungen. Plagiieren Sie proaktiv funktionalisierte Ergebnisse mit kostengünstigen Lösungen. Nutzen Sie gemeinsam webbasierte Infomediaries anstelle verschiedener Testverfahren.",
          fr: "Impactez continuellement des impératifs sans faille pour les meilleures pratiques. Facilitez phosphorescently les applications parallèles avec des impératifs uniques. Plagiez de manière proactive les livrables fonctionnalisés via des solutions peu coûteuses. Embrassez de manière collaborative des infomédiaires activés par le web plutôt que des procédures de test diverses.",
          ar: "أثر باستمرار على الضرورات السلسة لأفضل الممارسات. ساعد في تيسير التطبيقات الموازية بأهداف فريدة. نسخ النتائج المتخصصة بشكل نشط من خلال حلول ميسرة. اعتماد منهجية تعاونية لاستضافة معلومات الويب بدلاً من إجراءات الاختبار المتنوعة.",
        },
        faq_six: {
          en: "What are the benefits of using ZAPMarketplace affliate?",
          de: "Welche Vorteile bietet die Nutzung eines Cloud Clever-Partners?",
          fr: "Quels sont les avantages de l'utilisation de l'affilié ZAPMarketplace ?",
          ar: "ما هي فوائد استخدام شريك ZAPMarketplace؟",
        },
        description_six: {
          en: "Continually impact seamless imperatives for best-of-breed best practices. Phosfluorescently facilitate parallel applications with unique imperatives. Proactively plagiarize functionalized deliverables via inexpensive solutions. Collaboratively embrace web-enabled infomediaries rather than diverse testing procedures.",
          de: "Kontinuierliche Umsetzung nahtloser Anforderungen für Best-of-Breed-Best Practices. Phosfluoreszierend erleichtert parallele Anwendungen mit einzigartigen Anforderungen. Plagiieren Sie proaktiv funktionalisierte Ergebnisse mit kostengünstigen Lösungen. Nutzen Sie gemeinsam webbasierte Infomediaries anstelle verschiedener Testverfahren.",
          fr: "Impactez continuellement les impératifs sans couture pour les meilleures pratiques. Facilitez de manière phosfluorescente les applications parallèles avec des impératifs uniques. Plagiez de manière proactive des livrables fonctionnalisés via des solutions peu coûteuses. Adoptez de manière collaborative des infomédiaires activés par le web plutôt que des procédures de test diverses.",
          ar: "أثر باستمرار على الضرورات السلسة لأفضل الممارسات. قم بتيسير التطبيقات المتوازية بفعالية مع ضرورات فريدة. انسخ بصورة استباقية نتائج دقيقة وظيفية من خلال حلول اقتصادية. اعتمادًا على التعاون، قم بتبني وسطاء المعلومات المُمكّنين عبر الويب بدلاً من إجراءات الاختبار المتنوعة.",
        },
        faq_seven: {
          en: "What is a affiliates product configuration?",
          de: "Was ist eine Affiliate-Produktkonfiguration?",
          fr: "Qu'est-ce qu'une configuration de produit affilié ?",
          ar: "ما هي تكوينات المنتجات التابعة؟",
        },
        description_seven: {
          en: "Yes. You can cancel your subscription anytime. Your subscription will continue to be active until the end of your current term (month or year) but it will not auto-renew. Unless you delete your account manually, your account and all data will be deleted 60 days from the day your subscription becomes inactive.",
          de: "Ja. Sie können Ihr Abonnement jederzeit kündigen. Ihr Abonnement bleibt bis zum Ende Ihrer aktuellen Laufzeit (Monat oder Jahr) aktiv, verlängert sich jedoch nicht automatisch. Sofern Sie Ihr Konto nicht manuell löschen, werden Ihr Konto und alle Daten 60 Tage nach dem Tag, an dem Ihr Abonnement inaktiv wird, gelöscht.",
          fr: "Oui. Vous pouvez annuler votre abonnement à tout moment. Votre abonnement restera actif jusqu'à la fin de votre période en cours (mois ou année), mais il ne se renouvellera pas automatiquement. Sauf si vous supprimez votre compte manuellement, votre compte et toutes les données seront supprimés 60 jours après la date à laquelle votre abonnement devient inactif.",
          ar: "نعم، يمكنك إلغاء اشتراكك في أي وقت. سيظل اشتراكك نشطًا حتى نهاية الفترة الحالية (شهر أو سنة) ولكنه لن يتجدد تلقائيًا. ما لم تقم بحذف حسابك يدويًا، سيتم حذف حسابك وجميع البيانات بعد 60 يومًا من تاريخ تعطيل اشتراكك.",
        },
        faq_eight: {
          en: "What is fleet management and how is it different from dynamic scaling?",
          de: "Was ist Flottenmanagement und wie unterscheidet es sich von dynamischer Skalierung?",
          fr: "Qu'est-ce que la gestion de flotte et en quoi diffère-t-elle de la mise à l'échelle dynamique ?",
          ar: "ما هو إدارة الأسطول وكيف تختلف عن التوسيع الديناميكي؟",
        },
        description_eight: {
          en: "Distinctively initiate error-free channels with highly efficient ROI. Intrinsicly envisioneer world-class data via best-of-breed best practices. Efficiently enable empowered e-tailers after cross-unit services. Uniquely expedite seamless e-tailers via cooperative interfaces. Monotonectally myocardinate customer directed meta-services whereas error-free scenarios.",
          de: "Initiieren Sie gezielt fehlerfreie Kanäle mit hocheffizientem ROI. Stellen Sie sich durch branchenführende Best Practices erstklassige Daten vor. Ermöglichen Sie leistungsstarken E-Händlern auf effiziente Weise die Bereitstellung abteilungsübergreifender Dienstleistungen. Beschleunigen Sie nahtlose E-Tailer auf einzigartige Weise über kooperative Schnittstellen. Monotone myokardinierte kundengesteuerte Metadienste während fehlerfreier Szenarien.",
          fr: "Initiez de manière distinctive des canaux sans erreur avec un retour sur investissement très efficace. Envisionnez de manière intrinsèque des données de classe mondiale via les meilleures pratiques. Permettez efficacement aux e-commerçants autonomes après des services inter-unités. Accélérez de manière unique les e-commerçants sans couture via des interfaces coopératives. Myocardinez de manière monotonectale des méta-services dirigés par le client, tandis que les scénarios sont sans erreur.",
          ar: "قم ببدء القنوات خالية من الأخطاء بشكل مميز مع عائد استثمار فعّال للغاية. قم بتصوّر بشكل جوهري بيانات عالمية المستوى من خلال أفضل الممارسات. قم بتمكين التجار الإلكترونيين المميزين بفعالية بعد الخدمات بين الوحدات. قم بتسريع التجار الإلكترونيين الخاليين من الانقطاع بشكل فريد من خلال واجهات تعاونية. قم بتوجيه خدمات الزبائن بشكل مميت بينما تكون السيناريوهات خالية من الأخطاء.",
        },
      },
      slider: {
        left_right_arrow: false,
        bottom_dots: true,
        both_slider: false,
        first_img: "https://res.cloudinary.com/ahossain/image/upload/v1697688491/settings/slider-1_rl8qdc.jpg",
        first_title: {
          en: "The Best Quality Products Guaranteed!",
          de: "Die besten Qualitätsprodukte garantiert!",
          fr: "Les meilleurs produits de qualité garantis !",
          ar: "أفضل منتجات ذات جودة عالية مضمونة!",
        },
        first_description: {
          en: "The Best Quality Products Guaranteed!",
          de: "Die besten Qualitätsprodukte garantiert!",
          fr: "Les meilleurs produits de qualité garantis !",
          ar: "أفضل منتجات ذات جودة عالية مضمونة!",
        },
        first_button: {
          en: "Shop Now",
          de: "Jetzt einkaufen",
          fr: "Acheter maintenant",
          ar: "تسوق الآن",
        },
        second_title: {
          en: "Best Different Type of Grocery Store",
          de: "Bestes anderes Lebensmittelgeschäft",
          fr: "Meilleur type différent de magasin d'alimentation",
          ar: "أفضل نوع مختلف من متجر البقالة",
        },
        second_description: {
          en: "Quickly aggregate empowered networks after emerging products...",
          de: "Schnelle Bündelung leistungsstarker Netzwerke nach neuen Produkten ...",
          fr: "Regrouper rapidement des réseaux habilités après l'émergence de produits...",
          ar: "تجميع الشبكات الممكّنة بسرعة بعد ظهور المنتجات...",
        },
        second_button: {
          en: "Shop Now",
          de: "Jetzt einkaufen",
          fr: "Acheter maintenant",
          ar: "تسوق الآن",
        },
        third_title: {
          en: "Quality Freshness Guaranteed!",
          de: "Qualitätsfrische garantiert!",
          fr: "Fraîcheur de qualité garantie !",
          ar: "ضمان الجودة والنضارة!",
        },
        third_description: {
          en: "Intrinsicly fashion performance based products rather than accurate benefits...",
          de: "Gestalten Sie Produkte grundsätzlich auf Leistung und nicht auf konkrete Vorteile ...",
          fr: "Intrinsèquement façonner des produits basés sur la performance plutôt que des avantages précis...",
          ar: "بشكل أساسي تصميم منتجات تعتمد على الأداء بدلاً من الفوائد الدقيقة...",
        },
        third_button: {
          en: "Shop Now",
          de: "Jetzt einkaufen",
          fr: "Acheter maintenant",
          ar: "تسوق الآن",
        },
        four_title: {
          en: "The Best Quality Products Guaranteed!",
          de: "Die besten Qualitätsprodukte garantiert!",
          fr: "Les meilleurs produits de qualité garantis !",
          ar: "أفضل منتجات ذات جودة عالية مضمونة!",
        },
        four_description: {
          en: "Dramatically facilitate effective total linkage for go forward processes...",
          de: "Ermöglichen Sie eine effektive Gesamtverknüpfung für weitere Prozesse erheblich...",
          fr: "Facilitez de manière spectaculaire la liaison totale efficace pour les processus à venir...",
          ar: "تيسير الارتباط الكلي الفعّال بشكل كبير لعمليات التقدم...",
        },
        four_button: {
          en: "Shop Now",
          de: "Jetzt einkaufen",
          fr: "Acheter maintenant",
          ar: "تسوق الآن",
        },
        five_title: {
          en: "Best Different Type of Grocery Store",
          de: "Bestes anderes Lebensmittelgeschäft",
          fr: "Meilleur type différent de magasin d'alimentation",
          ar: "أفضل نوع مختلف من متجر البقالة",
        },
        five_description: {
          en: "Quickly aggregate empowered networks after emerging products...",
          de: "Schnelle Bündelung leistungsstarker Netzwerke nach neuen Produkten ...",
          fr: "Regrouper rapidement des réseaux habilités après l'émergence de produits...",
          ar: "تجميع الشبكات الممكّنة بسرعة بعد ظهور المنتجات...",
        },
        five_button: {
          en: "Shop Now",
          de: "Jetzt einkaufen",
          fr: "Acheter maintenant",
          ar: "تسوق الآن",
        },
        five_link: "/search?category=fish-meat",
      },
      checkout: {
        personal_details: {
          en: "Personal Details",
          de: "Persönliche Daten",
          fr: "Détails personnels",
          ar: "تفاصيل شخصية",
        },
        first_name: {
          en: "First Name",
          de: "Vorname",
          fr: "Prénom",
          ar: "الاسم الأول",
        },
        last_name: {
          en: "Last Name",
          de: "Familienname, Nachname",
          fr: "Nom de famille",
          ar: "الاسم الأخير",
        },
        email_address: {
          en: "Email Address",
          de: "E-Mail-Adresse",
          fr: "Adresse e-mail",
          ar: "عنوان البريد الإلكتروني",
        },
        checkout_phone: {
          en: "Phone Number",
          de: "Telefonnummer",
          fr: "Numéro de téléphone",
          ar: "رقم الهاتف",
        },
        shipping_details: {
          en: "Shipping Details",
          de: "Versanddetails",
          fr: "Détails de livraison",
          ar: "تفاصيل الشحن",
        },
        street_address: {
          en: "Street Address",
          de: "Straßenadresse",
          fr: "Adresse postale",
          ar: "عنوان الشارع",
        },
        city: {
          en: "City",
          de: "Stadt",
          fr: "Ville",
          ar: "مدينة",
        },
        country: {
          en: "Country",
          de: "Land",
          fr: "Pays",
          ar: "بلد",
        },
        zip_code: {
          en: "Zip Code",
          de: "PLZ",
          fr: "Code postal",
          ar: "الرمز البريدي",
        },
        shipping_cost: {
          en: "Shipping Cost",
          de: "Versandkosten",
          fr: "Frais de livraison",
          ar: "تكلفة الشحن",
        },
        payment_method: {
          en: "Payment Method",
          de: "Bezahlverfahren",
          fr: "Méthode de paiement",
          ar: "طريقة الدفع",
        },
        continue_button: {
          en: "Continue Shipping",
          de: "Weiterversand",
          fr: "Continuer la livraison",
          ar: "متابعة الشحن",
        },
        confirm_button: {
          en: "Confirm Order",
          de: "Bestellung bestätigen",
          fr: "Confirmer la commande",
          ar: "تأكيد الطلب",
        },
        order_summary: {
          en: "Order Summary",
          de: "Bestellübersicht",
          fr: "Résumé de la commande",
          ar: "ملخص الطلب",
        },
        apply_button: {
          en: "Apply",
          de: "Anwenden",
          fr: "Appliquer",
          ar: "تطبيق",
        },
        sub_total: {
          en: "Subtotal",
          de: "Zwischensumme",
          fr: "Sous-total",
          ar: "المجموع الفرعي",
        },
        discount: {
          en: "Discount",
          de: "Rabatt",
          fr: "Remise",
          ar: "خصم",
        },
        total_cost: {
          en: "TOTAL COST",
          de: "GESAMTKOSTEN",
          fr: "COÛT TOTAL",
          ar: "التكلفة الإجمالية",
        },
      },
      dashboard: {
        invoice_message_first: {
          en: "Thank You",
          de: "Danke",
          fr: "Merci",
          ar: "شكراً لك",
        },
        invoice_message_last: {
          en: "Your order have been received !",
          de: "Ihre Bestellung ist eingegangen!",
          fr: "Votre commande a été reçue !",
          ar: "تم استلام طلبك!",
        },
        print_button: {
          en: "Print Invoice",
          de: "Rechnung Drucken",
          fr: "Imprimer la facture",
          ar: "طباعة الفاتورة",
        },
        download_button: {
          en: "Download Invoice",
          de: "Download Rechnung",
          fr: "Télécharger la facture",
          ar: "تنزيل الفاتورة",
        },
        dashboard_title: {
          en: "Dashboard",
          de: "Armaturenbrett",
          fr: "Tableau de bord",
          ar: "لوحة القيادة",
        },
        total_order: {
          en: "Total Orders",
          de: "Gesamtbestellungen",
          fr: "Total des commandes",
          ar: "إجمالي الطلبات",
        },
        pending_order: {
          en: "Pending Orders",
          de: "Ausstehende Bestellungen",
          fr: "Commandes en attente",
          ar: "الطلبات المعلقة",
        },
        paid_order: {
          en: "Paid Orders",
          de: "Bezahlte Bestellungen",
          fr: "Commandes payées",
          ar: "الطلبات المدفوعة",
        },
        processing_order: {
          en: "Processing Order",
          de: "Bearbeitungsauftrag",
          fr: "Commande en traitement",
          ar: "طلب تحت المعالجة",
        },
        complete_order: {
          en: "Complete Orders",
          de: "Bestellungen abschließen",
          fr: "Commandes terminées",
          ar: "الطلبات المكتملة",
        },
        recent_order: {
          en: "Recent Orders",
          de: "letzte Bestellungen",
          fr: "Commandes récentes",
          ar: "الطلبات الأخيرة",
        },
        my_order: {
          en: "My Orders",
          de: "Meine Bestellungen",
          fr: "Mes commandes",
          ar: "طلباتي",
        },
        update_profile: {
          en: "Update Profile",
          de: "Profil aktualisieren",
          fr: "Mettre à jour le profil",
          ar: "تحديث الملف الشخصي",
        },
        full_name: {
          en: "Full Name",
          de: "Vollständiger Name",
          fr: "Nom complet",
          ar: "الاسم الكامل",
        },
        address: {
          en: "Address",
          de: "Adresse",
          fr: "Adresse",
          ar: "العنوان",
        },
        user_phone: {
          en: "Phone/Mobile",
          de: "Mobiltelefon",
          fr: "Téléphone/Portable",
          ar: "الهاتف/الجوال",
        },
        user_email: {
          en: "Email Address",
          de: "E-Mail-Adresse",
          fr: "Adresse e-mail",
          ar: "عنوان البريد الإلكتروني",
        },
        update_button: {
          en: "Update Profile",
          de: "Profil aktualisieren",
          fr: "Mettre à jour le profil",
          ar: "تحديث الملف الشخصي",
        },
        current_password: {
          en: "Current Password",
          de: "Aktuelles Passwort",
          fr: "Mot de passe actuel",
          ar: "كلمة المرور الحالية",
        },
        new_password: {
          en: "New Password",
          de: "Neues Kennwort",
          fr: "Nouveau mot de passe",
          ar: "كلمة مرور جديدة",
        },
        change_password: {
          en: "Change Password",
          de: "Kennwort ändern",
          fr: "Changer le mot de passe",
          ar: "تغيير كلمة المرور",
        },
      },
      footer: {
        promo_status: true,
        block1_status: true,
        block2_status: true,
        block3_status: true,
        block4_status: true,
        payment_method_status: true,
        bottom_contact_status: true,
        social_links_status: true,

        shipping_card: {
          en: "Free Shipping From €500.00",
          de: "Kostenloser Versand ab 500,00 €",
          fr: "Livraison gratuite à partir de 500,00 €",
          ar: "شحن مجاني للطلبات بقيمة 500.00 € أو أكثر",
        },
        support_card: {
          en: "Support 24/7 At Anytime",
          de: "Support rund um die Uhr und jederzeit",
          fr: "Assistance 24/7 à tout moment",
          ar: "دعم على مدار الساعة 24/7 في أي وقت",
        },
        payment_card: {
          en: "Secure Payment Totally Safe",
          de: "Sichere Zahlung, absolut sicher",
          fr: "Paiement sécurisé totalement sûr",
          ar: "دفع آمن ومضمون تمامًا",
        },
        offer_card: {
          en: "Latest Offer Upto 20% Off",
          de: "Aktuelles Angebot: Bis zu 20 % Rabatt",
          fr: "Dernière offre jusqu'à 20 % de réduction",
          ar: "أحدث عرض بخصم يصل إلى 20%",
        },
        block1_title: {
          en: "Company",
          de: "Unternehmen",
          fr: "Entreprise",
          ar: "الشركة",
        },
        block1_sub_title1: {
          en: "About Us",
          de: "Über uns",
          fr: "À propos de nous",
          ar: "معلومات عنا",
        },
        block1_sub_link1: "/about-us",
        block1_sub_title2: {
          en: "Contact Us",
          de: "Kontaktiere uns",
          fr: "Contactez-nous",
          ar: "اتصل بنا",
        },
        block1_sub_link2: "/contact-us",
        block1_sub_title3: {
          en: "Careers",
          de: "Karriere",
          fr: "Carrières",
          ar: "وظائف",
        },
        block1_sub_link3: "#",
        block1_sub_title4: {
          en: "Latest News",
          de: "Neueste Nachrichten",
          fr: "Dernières actualités",
          ar: "أحدث الأخبار",
        },
        block1_sub_link4: "#",
        block2_title: {
          en: "Latest News",
          de: "Neueste Nachrichten",
          fr: "Dernières actualités",
          ar: "أحدث الأخبار",
        },
        block2_sub_title1: {
          en: "Fish & Meat",
          de: "Fisch Fleisch",
          fr: "Poisson & Viande",
          ar: "أسماك ولحوم",
        },
        block2_sub_link1: "/search?category=fish-meat",
        block2_sub_title2: {
          en: "Soft Drink",
          de: "Erfrischungsgetränk",
          fr: "Boisson gazeuse",
          ar: "مشروبات غازية",
        },
        block2_sub_link2: "/search?category=drinks",
        block2_sub_title3: {
          en: "Milk & Dairy",
          de: "Milch und Milchprodukte",
          fr: "Lait & Produits laitiers",
          ar: "حليب ومنتجات ألبان",
        },
        block2_sub_link3: "/search?category=milk-dairy",
        block2_sub_title4: {
          en: "Beauty & Health",
          de: "Schönheit und Gesundheit",
          fr: "Beauté & Santé",
          ar: "جمال وصحة",
        },
        block2_sub_link4: "/search?category=beauty-health",
        block3_title: {
          en: "My Account",
          de: "Mein Konto",
          fr: "Mon compte",
          ar: "حسابي",
        },
        block3_sub_title1: {
          en: "Dashboard",
          de: "Armaturenbrett",
          fr: "Tableau de bord",
          ar: "لوحة القيادة",
        },
        block3_sub_link1: "/user/dashboard",
        block3_sub_title2: {
          en: "My Orders",
          de: "Meine Bestellungen",
          fr: "Mes commandes",
          ar: "طلباتي",
        },
        block3_sub_link2: "/user/my-orders",
        block3_sub_title3: {
          en: "Recent Orders",
          de: "letzte Bestellungen",
          fr: "Commandes récentes",
          ar: "الطلبات الأخيرة",
        },
        block3_sub_link3: "/user/dashboard",
        block3_sub_title4: {
          en: "Update Profile",
          de: "Profil aktualisieren",
          fr: "Mettre à jour le profil",
          ar: "تحديث الملف الشخصي",
        },
        block3_sub_link4: "/user/update-profile",
        block4_logo: "https://res.cloudinary.com/dapzqelui/image/upload/v1701429984/images/logo-color_el4zmy.svg",
        block4_address: {
          en: "987 Andre Plain Suite High Street 838, Lake Hestertown, USA",
          de: "987 Andre Plain Suite High Street 838, Lake Hestertown, USA",
          fr: "987 Andre Plain Suite High Street 838, Lake Hestertown, États-Unis",
          ar: "987 أندري بلين، جادة هاي ستريت 838، بحيرة هيسترتاون، الولايات المتحدة",
        },

        block4_phone: "02.356.1666",
        block4_email: "ccruidk@test.com",
        social_facebook: "https://www.facebook.com/",
        social_twitter: "https://twitter.com/",
        social_pinterest: "https://www.pinterest.com/",
        social_linkedin: "https://www.linkedin.com/",
        social_whatsapp: "https://web.whatsapp.com/",
        payment_method_img: "https://res.cloudinary.com/ahossain/image/upload/v1697688607/settings/payment-logo_qhslgz.webp",
        bottom_contact: "+6599887766",
      },

      slug: {
        right_box_status: true,
        card_description_one: {
          en: "Free shipping applies to all orders over shipping €100",
          de: "Kostenloser Versand gilt für alle Bestellungen über 100 € Versandkosten",
          fr: "Livraison gratuite pour toutes les commandes de plus de 100 € de frais de livraison",
          ar: "الشحن المجاني ينطبق على جميع الطلبات التي تزيد عن 100 يورو في تكلفة الشحن",
        },
        card_description_two: {
          en: "Home Delivery within 1 Hour",
          de: "Lieferung nach Hause innerhalb von 1 Stunde",
          fr: "Livraison à domicile en moins d'une heure",
          ar: "توصيل الطلب إلى المنزل في غضون ساعة واحدة",
        },
        card_description_three: {
          en: "Cash on Delivery Available",
          de: "Lieferung per Nachnahme möglich",
          fr: "Paiement à la livraison disponible",
          ar: "الدفع عند التسليم متاح",
        },
        card_description_four: {
          en: "7 Days returns money back guarantee",
          de: "7 Tage Geld-zurück-Garantie",
          fr: "Garantie de remboursement sous 7 jours",
          ar: "ضمان استرداد الأموال خلال 7 أيام",
        },
        card_description_five: {
          en: "Warranty not available for this item",
          de: "Für diesen Artikel ist keine Garantie verfügbar",
          fr: "Garantie non disponible pour cet article",
          ar: "الضمان غير متاح لهذا العنصر",
        },
        card_description_six: {
          en: "Guaranteed 100% organic from natural products.",
          de: "Garantiert 100 % biologisch aus Naturprodukten.",
          fr: "100 % biologique garanti à partir de produits naturels.",
          ar: "مضمون 100٪ عضوي من المنتجات الطبيعية.",
        },
        card_description_seven: {
          en: "Delivery from our pick point Boho One, Bridge Street West, Middlesbrough, North Yorkshire, TS2 1AE.",
          de: "Lieferung von unserem Abholpunkt Boho One, Bridge Street West, Middlesbrough, North Yorkshire, TS2 1AE.",
          fr: "Livraison depuis notre point de collecte Boho One, Bridge Street West, Middlesbrough, North Yorkshire, TS2 1AE.",
          ar: "توصيل من نقطة استلامنا في Boho One، Bridge Street West، Middlesbrough، North Yorkshire، TS2 1AE.",
        },
      },

      seo: {
        favicon: "https://res.cloudinary.com/dapzqelui/image/upload/v1701472670/images/favicon.png",
        meta_description: "Store e-commerce",
        meta_img: "https://res.cloudinary.com/dapzqelui/image/upload/v1701957157/images/facebook-page.png",
        meta_keywords: "e-commerce, online store",
        meta_title: "ZAPMarketplace - Store e-commerce",
        meta_url: "https://store.zapmarketplace.online/",
      },
    },
    name: "storeCustomizationSetting",
  },
  {
    setting: {
      cod_status: true,
      fb_pixel_key: "",
      fb_pixel_status: false,
      google_analytic_key: "G-6WWH1JTVRX",
      google_analytic_status: true,
      google_client_id: "747945671191-g6csbl01qmajt207i00e0vaqvc91347u.apps.googleusercontent.com",
      google_login_status: true,
      google_secret_key: "",
      stripe_key: "pk_test_51OHAFHHDrPjuXU4otWqPzJnLCEz5189rqZ4f2wTM9spdFizFBa1I5gIarUqkz9ESS4fuB527CYy7w7SQwal63njO00XhcS3jHdee",
      stripe_secret: "sk_test_51OHAFHHDrPjuXU4ofRN2elV29htwsfDpcUzTJUBQX2LUba75wkjVkJmft0Ue7iUFKNmFdRoctmXqGIQuykjVcvvB00bQ5xonnI",
      stripe_status: true,
      meta_url: "https://store.zapmarketplace.online/",
      tawk_chat_property_id: "6571c318ff45ca7d4787d774",
      tawk_chat_status: false,
      tawk_chat_widget_id: "1hh2646e4",
      external_integration_status: true,
      external_integration_api: "https://api.nomadis.com",
    },
    name: "storeSetting",
  },
];

module.exports = setting;
